# Generated by Django 5.0.1 on 2024-02-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_labtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(max_length=2000)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.labtest')),
            ],
        ),
    ]
