# Generated by Django 5.0.1 on 2024-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_labresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
