# Generated by Django 5.0.1 on 2024-02-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0007_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
