# Generated by Django 5.0.1 on 2024-02-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0010_solddrug_quantity_solddrug_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solddrug',
            name='total',
        ),
        migrations.AddField(
            model_name='solddrug',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solddrug',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
