# Generated by Django 5.0.1 on 2024-02-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0013_rename_total_amount_solddrug_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='solddrug',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='service_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('LabTest', 'Lab Test'), ('XRay', 'X-Ray'), ('DrugSale', 'Drug Sale')], max_length=20),
        ),
    ]
