# Generated by Django 5.0.1 on 2024-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0014_solddrug_status_alter_billing_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='solddrug',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solddrug',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
