# Generated by Django 5.0.1 on 2024-02-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0017_billing_drug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='drug',
            new_name='drug_invoice',
        ),
    ]
