# Generated by Django 5.0.1 on 2024-02-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0018_rename_drug_billing_drug_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.appointment'),
        ),
    ]
