# Generated by Django 5.0.1 on 2024-02-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0019_alter_billing_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='invoice_id',
            new_name='sold_drug',
        ),
    ]
