# Generated by Django 5.0.1 on 2024-02-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0023_prescription_prescribeddrug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribeddrug',
            name='dosage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescribeddrug',
            name='drug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescribeddrug',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescribeddrug',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
