# Generated by Django 5.0.1 on 2024-02-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0024_alter_prescribeddrug_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribeddrug',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
