# Generated by Django 5.0.1 on 2024-02-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0025_alter_prescribeddrug_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='card_number',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
