# Generated by Django 5.0.1 on 2024-03-01 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0027_alter_labresult_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='billing',
            name='service_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('LabTest', 'Lab Test'), ('XRay', 'X-Ray'), ('DrugSale', 'Drug Sale'), ('NewCard', 'New Card'), ('CardRenewal', 'Card Renewal')], max_length=20),
        ),
        migrations.AddField(
            model_name='billing',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.card'),
        ),
    ]
