# Generated by Django 5.0.1 on 2024-03-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0030_alter_cardprice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='is_card_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
