# Generated by Django 5.0.1 on 2024-03-05 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0032_card_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='mswd',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='xray_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='marriage_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widow', 'Widow(er)')], default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('in-patient', 'In-Patient'), ('out-patient', 'Out-Patient'), ('emergency', 'Emergency')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='registrar',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='card_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.card'),
        ),
    ]
