# Generated by Django 5.0.1 on 2024-03-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0033_remove_patient_mswd_remove_patient_xray_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
