# Generated by Django 5.0.1 on 2024-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0034_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ethnic_group',
            field=models.CharField(choices=[('igbo', 'Igbo'), ('hausa', 'Hausa'), ('yoruba', 'Yoruba'), ('afemai', 'Afemai'), ('akwa-ibom', 'Akwa Ibom'), ('akwaja', 'Akwaja'), ('afo', 'Afo'), ('anang', 'Anang'), ('basa', 'Basa'), ('bokyi', 'Bokyi'), ('ebira', 'Ebira'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('efik', 'Efik'), ('fulani', 'Fulani'), ('gobirawa', 'Gobirawa'), ('gbagyi', 'Gbagyi'), ('gbaya', 'Gbaya'), ('idoma', 'Idoma'), ('igala', 'Igala'), ('igalla', 'Igalla'), ('ijaw', 'Ijaw'), ('ijebu', 'Ijebu'), ('ijaw', 'Ijaw'), ('igede', 'Igede'), ('ikwerre', 'Ikwerre'), ('isoko', 'Isoko'), ('itsekiri', 'Itsekiri'), ('ijaw', 'Ijaw'), ('jukun', 'Jukun'), ('kaje', 'Kaje'), ('kanuri', 'Kanuri'), ('koro', 'Koro'), ('kuteb', 'Kuteb'), ('maghavul', 'Maghavul'), ('mbembe', 'Mbembe'), ('ngas', 'Ngas'), ('nupe', 'Nupe'), ('ogba', 'Ogba'), ('ogoja', 'Ogoja'), ('ogoni', 'Ogoni'), ('oromo', 'Oromo'), ('tiv', 'Tiv'), ('urhobo', 'Urhobo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='religion',
            field=models.CharField(choices=[('christainity', 'Christianity'), ('islam', 'Islam'), ('tradional', 'Tradional'), ('judaism', 'Judaism'), ('other', 'Other')], max_length=100),
        ),
    ]
