# Generated by Django 5.0.1 on 2024-03-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0035_alter_patient_ethnic_group_alter_patient_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Transfer')], max_length=20, null=True),
        ),
    ]
