# Generated by Django 5.0.1 on 2024-03-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0037_appointment_is_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_scheduled',
        ),
    ]
