# Generated by Django 5.0.1 on 2024-03-08 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0039_incomestream'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recorded', models.DateField()),
                ('income_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.incomestream')),
            ],
        ),
    ]
