# Generated by Django 5.0.1 on 2024-03-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0040_incomerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomerecord',
            old_name='date_recorded',
            new_name='created_at',
        ),
    ]
