# Generated by Django 5.0.1 on 2024-03-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0041_rename_date_recorded_incomerecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomerecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
