# Generated by Django 5.0.1 on 2024-03-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0042_alter_incomerecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
