# Generated by Django 5.0.1 on 2024-03-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0043_alter_incomerecord_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerecord',
            name='ref_code',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApprovedIncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('income_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.incomerecord')),
            ],
        ),
    ]
