# Generated by Django 5.0.1 on 2024-03-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0044_incomerecord_ref_code_approvedincomerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedincomerecord',
            old_name='income_record',
            new_name='ref_code',
        ),
        migrations.AlterField(
            model_name='incomerecord',
            name='ref_code',
            field=models.BigIntegerField(default=0),
        ),
    ]
