# Generated by Django 5.0.1 on 2024-03-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0045_rename_income_record_approvedincomerecord_ref_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
