# Generated by Django 5.0.1 on 2024-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0046_staff_is_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
