# Generated by Django 5.0.1 on 2024-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0048_alter_labresult_file_name_alter_labresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='weight',
            field=models.FloatField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='static/labresults/'),
        ),
    ]
